selenium:
    build:  selenium/
    expose:
        - "4444"
    ports:
        - "4444:4444"
    command:
        ./start.sh

apache:
    build: httpd/
    expose:
        - "80"
    volumes:
      - symfony:/var/www/symfony
      - logs:/var/log/apache2
    volumes_from:
        - symfonydata
    ports:
        - "8080:80"       
    links:
        - elasticmaster
    command:  
        ./start.sh

symfonydata:
    image: busybox
    volumes:
        - symfony/app/cache
        - symfony/app/logs

kibana:
  image: balsamiq/docker-kibana
  ports:
    - "9400:80"
  expose:
    - "9400"
  links:
    - elasticmaster:es
  environment:
    KIBANA_SECURE: false

elasticmaster:
    image: elasticsearch
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
      - elastic:/data
    command:
      elasticsearch  -Des.node.name=master -Des.node.master=true
      # elasticsearch -Des.config=/data/elasticsearch.yml -Des.node.name=master -Des.node.master=true

elasticslave1:
    image: elasticsearch
    volumes:
        - elastic:/data
    command:
        elasticsearch -Des.config=/data/elasticsearch.yml -Des.node.name=slave1 -Des.node.data=true -Des.node.master=false

elasticslave2:
    image: elasticsearch
    volumes:
        - elastic:/data
    command:
        elasticsearch -Des.config=/data/elasticsearch.yml -Des.node.name=slave2 -Des.node.data=true -Des.node.master=false
