apache:
    build: httpd/
    expose:
        - "80"
    volumes:
      - .:/var/www/symfony
    volumes_from:
        - data
    ports:
        - "8080:80"       
    command:  
        ./start.sh

data:
    image: busybox
    volumes:
        - app/cache
        - app/logs
