apache:
    build: httpd/
    expose:
        - "80"
    volumes:
      - symfony:/var/www/symfony
    volumes_from:
        - symfonydata
    ports:
        - "8080:80"       
    links:
        - elastic
    command:  
        ./start.sh

symfonydata:
    image: busybox
    volumes:
        - symfony/app/cache
        - symfony/app/logs

elastic:
    image: elasticsearch
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - esdata:/data

