af_home:
    resource: "@AFHomeBundle/Resources/config/routing.yml"
    prefix:   /

af_project:
    resource: @AFProjectBundle/Resources/config/routing.yml
    prefix:   /

af_bio:
  resource: @AFBioBundle/Resources/config/routing.yml
  prefix: /
 # host: me.ariasfreire.com
