af_home:
    resource: "@AFHomeBundle/Resources/config/routing.yml"
    host: web.%domain%

af_project:
    resource: "@AFProjectBundle/Resources/config/routing.yml"
    host: "project.%domain%"

af_bio:
  resource: "@AFBioBundle/Resources/config/routing.yml"
  host: "bio.%domain%"
