af_project:
    defaults: { _controller: AFProjectBundle:Project:index }
    path:   /

af_project_processor:
  defaults: { _controller: AFProjectBundle:Project:processor }
  path: /processor

af_project_data:
  defaults: { _controller: AFProjectBundle:Project:data }
  path: /data

af_project_project:
  defaults: { _controller: AFProjectBundle:Project:project }
  path: /project

af_project_final:
  defaults: { _controller: AFProjectBundle:Project:final }
  path: /final