af_project:
    defaults: { _controller: AFProjectBundle:Default:index }
    path:   /

af_project_scraper:
  defaults: { _controller: AFProjectBundle:Default:scraper }
  path: /scraper

af_project_data:
  defaults: { _controller: AFProjectBundle:Default:data }
  path: /data