parameters:
  shortProjectName: "Topic modeling GDELT historical data"
  projectDescription: "Distributed discovery of topics over GDELT data, using LDA algorithm from Spark's MLLib and Elastic Search"
